### ISSUE TITLE
min version not set as expected

### ISSUE THREAD

**Issue by jpschewe** [TheBoegl/gradle-launch4j#88]
The documentation for jreMinVersion says "project.targetCompatibility or the current java version, if the property is not set"

I've set sourceCompatibility and targetCompatibility is documented to default to sourceCompatibility if not set.

When I run my build with "-Pl4j-debug" so that I can examine the created XML file I find that minVersion is not set.

Setting targetCompatibility doesn't appear to cause the minVersion in the XML file to be populated either.

However adding "jreMinVersion = project.targetCompatibility" to the configuration for my createExe task causes the value to show up in the XML file.

Is this the expected behavior? If so, I expect the documentation should be updated to note that one needs to explicitly set the jreMinVersion.

**Comment by TheBoegl** [comment]
Sorry for that late response, I somehow missed this issue.

**Comment by TheBoegl** [comment]
I'm unable to reproduce this issue. In case this still happens please provide an minimal reproducible example.

**Comment by jpschewe** [comment]
@TheBoegl 

Here's a build.gradle file and the file that is produced.

```
// -*- java -*-

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
      // needs to use old plugin mechanism otherwise I can't set the extra properties   
      classpath(group: "com.cinnober.gradle", name: "semver-git", version: "3.0.0")
    }
}    

plugins {
    id "java"
    id "distribution"
    id "edu.sc.seis.launch4j" version "2.5.3"
}

// needs to use old plugin mechanism otherwise I can't set nextVersion and snapshotSuffix
ext.nextVersion = "patch"
ext.snapshotSuffix = "beta.<count>+g<sha><dirty>"
// optionally: ext.dirtyMarker = "-dirty" (default) replaces <dirty> in snapshotSuffix
// optionally: ext.gitDescribeArgs = '--match *[0-9].[0-9]*.[0-9]*' (default) or other arguments for git describe.
apply plugin: "com.cinnober.gradle.semver-git"

repositories {
    mavenCentral()
}

ext {
    log4j_version = "2.18.0"
    mainClassName = "fll.Launcher"
}


group = "fll"

java {
    // set version of Java that the source confirms to. 
    // The bytecode will be for this version of Java as well, unless targetCompatibility is specified.
    sourceCompatibility = JavaVersion.VERSION_17
}

createExe {
    mainClassName = project.mainClassName
    
    dontWrapJar = true
    errTitle = "FLL-SW"
    classpath = ["%EXEDIR%/classes", "%EXEDIR%/lib/*.jar"]
    // need to specify a jar file that we know will exist as a dependency, 
    // otherwise launch4j will look for the jar file created from the build
    jar = "lib/log4j-core-" + project.log4j_version + ".jar"
    
    maxHeapPercent = 75        
    
    fileDescription = "FIRST Lego League Scoring Software"
    productName = "FLL-SW"
    copyright = "GPL"
    
    bundledJrePath = "jdk"
    bundledJre64Bit = true
    bundledJreAsFallback = false

    // should not need to specify this https://github.com/TheBoegl/gradle-launch4j/issues/88        
    //jreMinVersion = project.targetCompatibility
    
    // for debugging classpath information        
    //headerType = "console"
    jvmOptions = [
    //"-Dlog4j2.debug=true",
    
    // Add the JAVA 9 specific start-up parameters required by Tomcat
    "--add-opens=java.base/java.lang=ALL-UNNAMED",
    "--add-opens=java.base/java.io=ALL-UNNAMED",
    "--add-opens=java.base/java.util=ALL-UNNAMED",
    "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED",
    "--add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
    ]
}
```

Output
```
<?xml version='1.0' encoding='UTF-8'?>
<launch4jConfig>
  <dontWrapJar>true</dontWrapJar>
  <headerType>gui</headerType>
  <jar>lib/log4j-core-2.18.0.jar</jar>
  <outfile>launch4j.88.exe</outfile>
  <errTitle>FLL-SW</errTitle>
  <cmdLine></cmdLine>
  <chdir>.</chdir>
  <priority>normal</priority>
  <downloadUrl>http://java.com/download</downloadUrl>
  <supportUrl></supportUrl>
  <stayAlive>false</stayAlive>
  <restartOnCrash>false</restartOnCrash>
  <manifest></manifest>
  <icon></icon>
  <classPath>
    <mainClass>fll.Launcher</mainClass>
    <cp>%EXEDIR%/classes</cp>
    <cp>%EXEDIR%/lib/*.jar</cp>
  </classPath>
  <jre>
    <path>jdk</path>
    <bundledJre64Bit>true</bundledJre64Bit>
    <bundledJreAsFallback>false</bundledJreAsFallback>
    <minVersion></minVersion>
    <maxVersion></maxVersion>
    <jdkPreference>preferJre</jdkPreference>
    <runtimeBits>64/32</runtimeBits>
    <opt>--add-opens=java.base/java.lang=ALL-UNNAMED</opt>
    <opt>--add-opens=java.base/java.io=ALL-UNNAMED</opt>
    <opt>--add-opens=java.base/java.util=ALL-UNNAMED</opt>
    <opt>--add-opens=java.base/java.util.concurrent=ALL-UNNAMED</opt>
    <opt>--add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED</opt>
    <maxHeapPercent>75</maxHeapPercent>
  </jre>
  <versionInfo>
    <fileVersion>0.0.0.1</fileVersion>
    <txtFileVersion>unspecified</txtFileVersion>
    <fileDescription>FIRST Lego League Scoring Software</fileDescription>
    <copyright>GPL</copyright>
    <productVersion>0.0.0.1</productVersion>
    <txtProductVersion>unspecified</txtProductVersion>
    <productName>FLL-SW</productName>
    <companyName></companyName>
    <internalName>launch4j.88</internalName>
    <originalFilename>launch4j.88.exe</originalFilename>
    <trademarks></trademarks>
    <language>ENGLISH_US</language>
  </versionInfo>
</launch4jConfig>
```

Note that the "minVersion" tag is empty.

I created this using `gradlew -Pl4j-debug createExe `
```
gradlew --version

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Private Build 17.0.5+8-Ubuntu-2ubuntu122.04)
OS:           Linux 6.0.6-76060006-generic amd64
```

**Comment by jpschewe** [comment]
@TheBoegl  what is different about our environments? I'm seeing an empty minVersion tag, however your test case is passing. I downloaded your repository and see that you are using gradle 6.9.5. When I execute the check task with that on my system using Java 17 I get
```
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
...
```

When I execute the check task with gradle 7.5.1 I get
```
> Task :compileJava NO-SOURCE
> Task :compileGroovy
> Task :pluginDescriptors
> Task :processResources
> Task :classes
> Task :createClasspathManifest
> Task :pluginUnderTestMetadata
> Task :compileTestJava NO-SOURCE

> Task :compileTestGroovy FAILED
startup failed:
Could not instantiate global transform class org.spockframework.compiler.SpockTransform specified at jar:file:/home/jpschewe/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/1.3-groovy-2.5/6f0df2cf4549dcc4b914971675da7e224e893e82/spock-core-1.3-groovy-2.5.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception org.spockframework.util.IncompatibleGroovyVersionException: The Spock compiler plugin cannot execute because Spock 1.3.0-groovy-2.5 is not compatible with Groovy 3.0.10. For more information, see http://versioninfo.spockframework.org
Spock artifact: file:/home/jpschewe/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/1.3-groovy-2.5/6f0df2cf4549dcc4b914971675da7e224e893e82/spock-core-1.3-groovy-2.5.jar
Groovy artifact: file:/home/jpschewe/.gradle/wrapper/dists/gradle-7.5.1-bin/7jzzequgds1hbszbhq3npc5ng/gradle-7.5.1/lib/groovy-3.0.10.jar

1 error

```

**Comment by TheBoegl** [comment]
@jpschewe currently this plugin only works with gradle 6 and groovy 2.5 as I didn't get the tests to work with groovy 3 required by gradle 7.
I've tested your provided example above in a different project with the same gradle version as you did and can reproduce this issue, though I haven't figured out why this is happening...

**Comment by jpschewe** [comment]
@TheBoegl glad you can reproduce it, sorry to hear you don't have an answer for the tests not running. I tried using spock 2.0-grooby3.0 and found the tests didn't run at all. I'm assuming that's what you did as well. I do see some notes on the web about spock 2.0 using JUnit platform (possibly the same as juint 5?) and that may require some changes.

**Comment by jpschewe** [comment]
However I did note that a number of the tests fail for me when executed under Java 8 and gradle 6. Perhaps they require running on Windows?

**Comment by TheBoegl** [comment]
Could you please post a build scan or attach the failing tests. The tests should run on Linux except aarch64 (see #90) as well.

**Comment by TheBoegl** [comment]
I have to clarify that the many tests execute the created exe, which for obvious reasons cannot work in non Windows operating systems.

**Comment by jpschewe** [comment]
```
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :compileJava NO-SOURCE
> Task :compileGroovy
> Task :pluginDescriptors
> Task :processResources
> Task :classes
> Task :createClasspathManifest
> Task :pluginUnderTestMetadata
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy
> Task :processTestResources
> Task :testClasses

> Task :test

edu.sc.seis.launch4j.Issue43Test > Running the task to create the executable with a relative icon and splash path succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue43Test.groovy:75

edu.sc.seis.launch4j.Issue43Test > Running the task to create the executable with an absolute icon and splash path succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue43Test.groovy:122

edu.sc.seis.launch4j.Issue43Test > Running the task to create the executable without an icon or splash file succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue43Test.groovy:166

edu.sc.seis.launch4j.Issue59Test > Check that the variables are set and retrieved correctly FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue59Test.groovy:66

edu.sc.seis.launch4j.Issue46Test > Running the task to create the executable with the deprecated opt for language de succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue46Test.groovy:72

edu.sc.seis.launch4j.Issue46Test > Running the task to create the executable with the deprecated opt for language en succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue46Test.groovy:72

edu.sc.seis.launch4j.Issue46Test > Running the task to create the executable with jvmOptions for language de succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue46Test.groovy:127

edu.sc.seis.launch4j.Issue46Test > Running the task to create the executable with jvmOptions for language en succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue46Test.groovy:127

edu.sc.seis.launch4j.Issue46Test > Running the task to create the executable without jvm options succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue46Test.groovy:174

edu.sc.seis.launch4j.Issue78Test > Check that implementation dependencies work as expected FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue78Test.groovy:65

edu.sc.seis.launch4j.Issue72Test > Check that JRE 10 is allowed in maxVersion FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue72Test.groovy:65

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running the created executable succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:317

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running the created executable with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:363

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running the created executable in a subfolder with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:411

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running the created executable in a subfolder and default lib folder with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:459

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running the created executable in a subfolder and changed lib folder with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:508

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running an unwrapped executable with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:570

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running an unwrapped executable jar as executable with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:632

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running a fat executable jar as executable with Java dependencies succeeds FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:699

edu.sc.seis.launch4j.Launch4jPluginExtensionTest > Running a fat executable shadowJar as executable with Java dependencies succeeds with shadowJar task FAILED
    org.spockframework.runtime.SpockComparisonFailure at Launch4jPluginExtensionTest.groovy:767

edu.sc.seis.launch4j.Issue83Test > setting only the path is possible FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue83Test.groovy:69

edu.sc.seis.launch4j.Issue79Test > Check that setting chdir to empty string does not use default value FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue79Test.groovy:44

edu.sc.seis.launch4j.Issue79Test > Check that not setting chdir uses default value FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue79Test.groovy:88

edu.sc.seis.launch4j.Issue77Test > Check that dontWrapJar is overwritten FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue77Test.groovy:77

edu.sc.seis.launch4j.Issue77Test > Check that the default createExe is not wrapped FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue77Test.groovy:120

edu.sc.seis.launch4j.Issue117Test > Check EXCLUDE duplication Strategy FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue117Test.groovy:36

edu.sc.seis.launch4j.Issue117Test > Check default duplication Strategy FAILED
    org.spockframework.runtime.SpockComparisonFailure at Issue117Test.groovy:66

43 tests completed, 27 failed
```

**Comment by TheBoegl** [comment]
@jpschewe can you please verify that the [latest development](/TheBoegl/gradle-launch4j#using-snapshot-versions) version 3.0.0-SNAPSHOT works for you? The test cases pass and my adjusted test project from your [comment](88#issuecomment-1356496135)  seems to work as intended after removing the property `bundledJreAsFallback` and migrate `bundledJre64Bit` to `requires64Bit` to avoid the warning on every run.

**Comment by jpschewe** [comment]
@TheBoegl  something else changed in the handling. I made the changes you requested to my build file and I got an error.

build file
```
// -*- java -*-

buildscript {
    repositories {
        maven { url 'https://boegl.jfrog.io/artifactory/snapshots-gradle-dev-local/' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'edu.sc.seis.launch4j:launch4j:latest.integration'
        
      // needs to use old plugin mechanism otherwise I can't set the extra properties   
      classpath(group: "com.cinnober.gradle", name: "semver-git", version: "3.0.0")
    }
}    

plugins {
    id "java"
    id "distribution"
    //id "edu.sc.seis.launch4j" version "2.5.3"
}

// needs to use old plugin mechanism otherwise I can't set nextVersion and snapshotSuffix
ext.nextVersion = "patch"
ext.snapshotSuffix = "beta.<count>+g<sha><dirty>"
// optionally: ext.dirtyMarker = "-dirty" (default) replaces <dirty> in snapshotSuffix
// optionally: ext.gitDescribeArgs = '--match *[0-9].[0-9]*.[0-9]*' (default) or other arguments for git describe.
apply plugin: "com.cinnober.gradle.semver-git"

apply plugin: 'edu.sc.seis.launch4j'


repositories {
    mavenCentral()
}

ext {
    log4j_version = "2.18.0"
    mainClassName = "fll.Launcher"
}


group = "fll"

java {
    // set version of Java that the source confirms to. 
    // The bytecode will be for this version of Java as well, unless targetCompatibility is specified.
    sourceCompatibility = JavaVersion.VERSION_17
}

createExe {
    mainClassName = project.mainClassName
    
    dontWrapJar = true
    errTitle = "FLL-SW"
    classpath = ["%EXEDIR%/classes", "%EXEDIR%/lib/*.jar"]
    // need to specify a jar file that we know will exist as a dependency, 
    // otherwise launch4j will look for the jar file created from the build
    jar = "lib/log4j-core-" + project.log4j_version + ".jar"
    
    maxHeapPercent = 75        
    
    fileDescription = "FIRST Lego League Scoring Software"
    productName = "FLL-SW"
    copyright = "GPL"
    
    bundledJrePath = "jdk"
    //bundledJre64Bit = true
    requires64Bit = true
    //bundledJreAsFallback = false

    // should not need to specify this https://github.com/TheBoegl/gradle-launch4j/issues/88        
    //jreMinVersion = project.targetCompatibility
    
    // for debugging classpath information        
    //headerType = "console"
    jvmOptions = [
    //"-Dlog4j2.debug=true",
    
    // Add the JAVA 9 specific start-up parameters required by Tomcat
    "--add-opens=java.base/java.lang=ALL-UNNAMED",
    "--add-opens=java.base/java.io=ALL-UNNAMED",
    "--add-opens=java.base/java.util=ALL-UNNAMED",
    "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED",
    "--add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
    ]
}
```

output
```

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jpschewe/projects/launch4j-bugs/88/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating root project '88'.
> Could not set unknown property 'jar' for task ':createExe' of type edu.sc.seis.launch4j.tasks.Launch4jLibraryTask.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

Gradle version information
```

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Private Build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
OS:           Linux 6.2.6-76060206-generic amd64
```

**Comment by TheBoegl** [comment]
The jar property was replaced with jarTask or copyConfuguration.
I've missed adding that to the removed properties in the readme.
